name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on PRs targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    # Build the project using Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    # Run tests to ensure the application is working correctly
    - name: Run tests
      run: mvn test

    # Package the application into a JAR file
    - name: Build JAR
      run: mvn package

    # Optional: Deploy to Staging (You can replace this with your actual deployment process)
    - name: Deploy to Staging
      run: |
        echo "Deploying to Staging..."
        # Add your actual deployment commands here
        # For example: scp target/your-app.jar user@staging-server:/path/to/deploy
        # ssh user@staging-server "bash /path/to/deploy/deploy-script.sh"

    # Optional: Deploy to Production (This step is triggered only on push to main branch)
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "Deploying to Production..."
        # Add your actual deployment commands for the production environment here
        # Example: scp target/your-app.jar user@production-server:/path/to/deploy
        # ssh user@production-server "bash /path/to/deploy/deploy-script.sh"
